/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables.records;


import com.fkfc.generatedsources.entity.tables.Receita;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceitaRecord extends UpdatableRecordImpl<ReceitaRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1032647488;

    /**
     * Setter for <code>receitas.receita.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>receitas.receita.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>receitas.receita.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>receitas.receita.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>receitas.receita.modo_preparo</code>.
     */
    public void setModoPreparo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>receitas.receita.modo_preparo</code>.
     */
    public String getModoPreparo() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Receita.RECEITA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Receita.RECEITA.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Receita.RECEITA.MODO_PREPARO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getModoPreparo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getModoPreparo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceitaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceitaRecord value2(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceitaRecord value3(String value) {
        setModoPreparo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceitaRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReceitaRecord
     */
    public ReceitaRecord() {
        super(Receita.RECEITA);
    }

    /**
     * Create a detached, initialised ReceitaRecord
     */
    public ReceitaRecord(Integer id, String nome, String modoPreparo) {
        super(Receita.RECEITA);

        set(0, id);
        set(1, nome);
        set(2, modoPreparo);
    }
}
