/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity;


import com.fkfc.generatedsources.entity.tables.Categoria;
import com.fkfc.generatedsources.entity.tables.Ingrediente;
import com.fkfc.generatedsources.entity.tables.Metadado;
import com.fkfc.generatedsources.entity.tables.Receita;
import com.fkfc.generatedsources.entity.tables.ReceitaCategoria;
import com.fkfc.generatedsources.entity.tables.ReceitaIngrediente;
import com.fkfc.generatedsources.entity.tables.ReceitaMetadado;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>receitas</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CATEGORIA_PRIMARY = Indexes0.CATEGORIA_PRIMARY;
    public static final Index INGREDIENTE_PRIMARY = Indexes0.INGREDIENTE_PRIMARY;
    public static final Index METADADO_PRIMARY = Indexes0.METADADO_PRIMARY;
    public static final Index RECEITA_PRIMARY = Indexes0.RECEITA_PRIMARY;
    public static final Index RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_CATEGORIA1_IDX = Indexes0.RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_CATEGORIA1_IDX;
    public static final Index RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_RECEITA1_IDX = Indexes0.RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_RECEITA1_IDX;
    public static final Index RECEITA_CATEGORIA_PRIMARY = Indexes0.RECEITA_CATEGORIA_PRIMARY;
    public static final Index RECEITA_INGREDIENTE_FK_RECEITA_INGREDIENTE_INGREDIENTE1_IDX = Indexes0.RECEITA_INGREDIENTE_FK_RECEITA_INGREDIENTE_INGREDIENTE1_IDX;
    public static final Index RECEITA_INGREDIENTE_FK_RECEITA_INGREDIENTE_RECEITA1_IDX = Indexes0.RECEITA_INGREDIENTE_FK_RECEITA_INGREDIENTE_RECEITA1_IDX;
    public static final Index RECEITA_INGREDIENTE_PRIMARY = Indexes0.RECEITA_INGREDIENTE_PRIMARY;
    public static final Index RECEITA_METADADO_FK_RECEITA_METADADO_RECEITA1_IDX = Indexes0.RECEITA_METADADO_FK_RECEITA_METADADO_RECEITA1_IDX;
    public static final Index RECEITA_METADADO_FK_RECEITA_METADADO_TIPO_METADADO1_IDX = Indexes0.RECEITA_METADADO_FK_RECEITA_METADADO_TIPO_METADADO1_IDX;
    public static final Index RECEITA_METADADO_PRIMARY = Indexes0.RECEITA_METADADO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CATEGORIA_PRIMARY = Internal.createIndex("PRIMARY", Categoria.CATEGORIA, new OrderField[] { Categoria.CATEGORIA.ID }, true);
        public static Index INGREDIENTE_PRIMARY = Internal.createIndex("PRIMARY", Ingrediente.INGREDIENTE, new OrderField[] { Ingrediente.INGREDIENTE.ID }, true);
        public static Index METADADO_PRIMARY = Internal.createIndex("PRIMARY", Metadado.METADADO, new OrderField[] { Metadado.METADADO.ID }, true);
        public static Index RECEITA_PRIMARY = Internal.createIndex("PRIMARY", Receita.RECEITA, new OrderField[] { Receita.RECEITA.ID }, true);
        public static Index RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_CATEGORIA1_IDX = Internal.createIndex("fk_receita_categoria_categoria1_idx", ReceitaCategoria.RECEITA_CATEGORIA, new OrderField[] { ReceitaCategoria.RECEITA_CATEGORIA.CATEGORIA_ID }, false);
        public static Index RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_RECEITA1_IDX = Internal.createIndex("fk_receita_categoria_receita1_idx", ReceitaCategoria.RECEITA_CATEGORIA, new OrderField[] { ReceitaCategoria.RECEITA_CATEGORIA.RECEITA_ID }, false);
        public static Index RECEITA_CATEGORIA_PRIMARY = Internal.createIndex("PRIMARY", ReceitaCategoria.RECEITA_CATEGORIA, new OrderField[] { ReceitaCategoria.RECEITA_CATEGORIA.RECEITA_ID, ReceitaCategoria.RECEITA_CATEGORIA.CATEGORIA_ID }, true);
        public static Index RECEITA_INGREDIENTE_FK_RECEITA_INGREDIENTE_INGREDIENTE1_IDX = Internal.createIndex("fk_receita_ingrediente_ingrediente1_idx", ReceitaIngrediente.RECEITA_INGREDIENTE, new OrderField[] { ReceitaIngrediente.RECEITA_INGREDIENTE.INGREDIENTE_ID }, false);
        public static Index RECEITA_INGREDIENTE_FK_RECEITA_INGREDIENTE_RECEITA1_IDX = Internal.createIndex("fk_receita_ingrediente_receita1_idx", ReceitaIngrediente.RECEITA_INGREDIENTE, new OrderField[] { ReceitaIngrediente.RECEITA_INGREDIENTE.RECEITA_ID }, false);
        public static Index RECEITA_INGREDIENTE_PRIMARY = Internal.createIndex("PRIMARY", ReceitaIngrediente.RECEITA_INGREDIENTE, new OrderField[] { ReceitaIngrediente.RECEITA_INGREDIENTE.RECEITA_ID, ReceitaIngrediente.RECEITA_INGREDIENTE.INGREDIENTE_ID }, true);
        public static Index RECEITA_METADADO_FK_RECEITA_METADADO_RECEITA1_IDX = Internal.createIndex("fk_receita_metadado_receita1_idx", ReceitaMetadado.RECEITA_METADADO, new OrderField[] { ReceitaMetadado.RECEITA_METADADO.RECEITA_ID }, false);
        public static Index RECEITA_METADADO_FK_RECEITA_METADADO_TIPO_METADADO1_IDX = Internal.createIndex("fk_receita_metadado_tipo_metadado1_idx", ReceitaMetadado.RECEITA_METADADO, new OrderField[] { ReceitaMetadado.RECEITA_METADADO.METADADO_ID }, false);
        public static Index RECEITA_METADADO_PRIMARY = Internal.createIndex("PRIMARY", ReceitaMetadado.RECEITA_METADADO, new OrderField[] { ReceitaMetadado.RECEITA_METADADO.METADADO_ID, ReceitaMetadado.RECEITA_METADADO.RECEITA_ID }, true);
    }
}
