/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity;


import com.fkfc.generatedsources.entity.tables.Categoria;
import com.fkfc.generatedsources.entity.tables.Ingrediente;
import com.fkfc.generatedsources.entity.tables.Metadado;
import com.fkfc.generatedsources.entity.tables.Receita;
import com.fkfc.generatedsources.entity.tables.ReceitaCategoria;
import com.fkfc.generatedsources.entity.tables.ReceitaIngrediente;
import com.fkfc.generatedsources.entity.tables.ReceitaMetadado;
import com.fkfc.generatedsources.entity.tables.records.CategoriaRecord;
import com.fkfc.generatedsources.entity.tables.records.IngredienteRecord;
import com.fkfc.generatedsources.entity.tables.records.MetadadoRecord;
import com.fkfc.generatedsources.entity.tables.records.ReceitaCategoriaRecord;
import com.fkfc.generatedsources.entity.tables.records.ReceitaIngredienteRecord;
import com.fkfc.generatedsources.entity.tables.records.ReceitaMetadadoRecord;
import com.fkfc.generatedsources.entity.tables.records.ReceitaRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>receitas</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CategoriaRecord, Integer> IDENTITY_CATEGORIA = Identities0.IDENTITY_CATEGORIA;
    public static final Identity<IngredienteRecord, Integer> IDENTITY_INGREDIENTE = Identities0.IDENTITY_INGREDIENTE;
    public static final Identity<MetadadoRecord, Integer> IDENTITY_METADADO = Identities0.IDENTITY_METADADO;
    public static final Identity<ReceitaRecord, Integer> IDENTITY_RECEITA = Identities0.IDENTITY_RECEITA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoriaRecord> KEY_CATEGORIA_PRIMARY = UniqueKeys0.KEY_CATEGORIA_PRIMARY;
    public static final UniqueKey<IngredienteRecord> KEY_INGREDIENTE_PRIMARY = UniqueKeys0.KEY_INGREDIENTE_PRIMARY;
    public static final UniqueKey<MetadadoRecord> KEY_METADADO_PRIMARY = UniqueKeys0.KEY_METADADO_PRIMARY;
    public static final UniqueKey<ReceitaRecord> KEY_RECEITA_PRIMARY = UniqueKeys0.KEY_RECEITA_PRIMARY;
    public static final UniqueKey<ReceitaCategoriaRecord> KEY_RECEITA_CATEGORIA_PRIMARY = UniqueKeys0.KEY_RECEITA_CATEGORIA_PRIMARY;
    public static final UniqueKey<ReceitaIngredienteRecord> KEY_RECEITA_INGREDIENTE_PRIMARY = UniqueKeys0.KEY_RECEITA_INGREDIENTE_PRIMARY;
    public static final UniqueKey<ReceitaMetadadoRecord> KEY_RECEITA_METADADO_PRIMARY = UniqueKeys0.KEY_RECEITA_METADADO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ReceitaCategoriaRecord, ReceitaRecord> FK_RECEITA_CATEGORIA_RECEITA1 = ForeignKeys0.FK_RECEITA_CATEGORIA_RECEITA1;
    public static final ForeignKey<ReceitaCategoriaRecord, CategoriaRecord> FK_RECEITA_CATEGORIA_CATEGORIA1 = ForeignKeys0.FK_RECEITA_CATEGORIA_CATEGORIA1;
    public static final ForeignKey<ReceitaIngredienteRecord, ReceitaRecord> FK_RECEITA_INGREDIENTE_RECEITA1 = ForeignKeys0.FK_RECEITA_INGREDIENTE_RECEITA1;
    public static final ForeignKey<ReceitaIngredienteRecord, IngredienteRecord> FK_RECEITA_INGREDIENTE_INGREDIENTE1 = ForeignKeys0.FK_RECEITA_INGREDIENTE_INGREDIENTE1;
    public static final ForeignKey<ReceitaMetadadoRecord, ReceitaRecord> FK_RECEITA_METADADO_RECEITA1 = ForeignKeys0.FK_RECEITA_METADADO_RECEITA1;
    public static final ForeignKey<ReceitaMetadadoRecord, MetadadoRecord> FK_RECEITA_METADADO_TIPO_METADADO1 = ForeignKeys0.FK_RECEITA_METADADO_TIPO_METADADO1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CategoriaRecord, Integer> IDENTITY_CATEGORIA = Internal.createIdentity(Categoria.CATEGORIA, Categoria.CATEGORIA.ID);
        public static Identity<IngredienteRecord, Integer> IDENTITY_INGREDIENTE = Internal.createIdentity(Ingrediente.INGREDIENTE, Ingrediente.INGREDIENTE.ID);
        public static Identity<MetadadoRecord, Integer> IDENTITY_METADADO = Internal.createIdentity(Metadado.METADADO, Metadado.METADADO.ID);
        public static Identity<ReceitaRecord, Integer> IDENTITY_RECEITA = Internal.createIdentity(Receita.RECEITA, Receita.RECEITA.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CategoriaRecord> KEY_CATEGORIA_PRIMARY = Internal.createUniqueKey(Categoria.CATEGORIA, "KEY_categoria_PRIMARY", Categoria.CATEGORIA.ID);
        public static final UniqueKey<IngredienteRecord> KEY_INGREDIENTE_PRIMARY = Internal.createUniqueKey(Ingrediente.INGREDIENTE, "KEY_ingrediente_PRIMARY", Ingrediente.INGREDIENTE.ID);
        public static final UniqueKey<MetadadoRecord> KEY_METADADO_PRIMARY = Internal.createUniqueKey(Metadado.METADADO, "KEY_metadado_PRIMARY", Metadado.METADADO.ID);
        public static final UniqueKey<ReceitaRecord> KEY_RECEITA_PRIMARY = Internal.createUniqueKey(Receita.RECEITA, "KEY_receita_PRIMARY", Receita.RECEITA.ID);
        public static final UniqueKey<ReceitaCategoriaRecord> KEY_RECEITA_CATEGORIA_PRIMARY = Internal.createUniqueKey(ReceitaCategoria.RECEITA_CATEGORIA, "KEY_receita_categoria_PRIMARY", ReceitaCategoria.RECEITA_CATEGORIA.RECEITA_ID, ReceitaCategoria.RECEITA_CATEGORIA.CATEGORIA_ID);
        public static final UniqueKey<ReceitaIngredienteRecord> KEY_RECEITA_INGREDIENTE_PRIMARY = Internal.createUniqueKey(ReceitaIngrediente.RECEITA_INGREDIENTE, "KEY_receita_ingrediente_PRIMARY", ReceitaIngrediente.RECEITA_INGREDIENTE.RECEITA_ID, ReceitaIngrediente.RECEITA_INGREDIENTE.INGREDIENTE_ID);
        public static final UniqueKey<ReceitaMetadadoRecord> KEY_RECEITA_METADADO_PRIMARY = Internal.createUniqueKey(ReceitaMetadado.RECEITA_METADADO, "KEY_receita_metadado_PRIMARY", ReceitaMetadado.RECEITA_METADADO.METADADO_ID, ReceitaMetadado.RECEITA_METADADO.RECEITA_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ReceitaCategoriaRecord, ReceitaRecord> FK_RECEITA_CATEGORIA_RECEITA1 = Internal.createForeignKey(com.fkfc.generatedsources.entity.Keys.KEY_RECEITA_PRIMARY, ReceitaCategoria.RECEITA_CATEGORIA, "fk_receita_categoria_receita1", ReceitaCategoria.RECEITA_CATEGORIA.RECEITA_ID);
        public static final ForeignKey<ReceitaCategoriaRecord, CategoriaRecord> FK_RECEITA_CATEGORIA_CATEGORIA1 = Internal.createForeignKey(com.fkfc.generatedsources.entity.Keys.KEY_CATEGORIA_PRIMARY, ReceitaCategoria.RECEITA_CATEGORIA, "fk_receita_categoria_categoria1", ReceitaCategoria.RECEITA_CATEGORIA.CATEGORIA_ID);
        public static final ForeignKey<ReceitaIngredienteRecord, ReceitaRecord> FK_RECEITA_INGREDIENTE_RECEITA1 = Internal.createForeignKey(com.fkfc.generatedsources.entity.Keys.KEY_RECEITA_PRIMARY, ReceitaIngrediente.RECEITA_INGREDIENTE, "fk_receita_ingrediente_receita1", ReceitaIngrediente.RECEITA_INGREDIENTE.RECEITA_ID);
        public static final ForeignKey<ReceitaIngredienteRecord, IngredienteRecord> FK_RECEITA_INGREDIENTE_INGREDIENTE1 = Internal.createForeignKey(com.fkfc.generatedsources.entity.Keys.KEY_INGREDIENTE_PRIMARY, ReceitaIngrediente.RECEITA_INGREDIENTE, "fk_receita_ingrediente_ingrediente1", ReceitaIngrediente.RECEITA_INGREDIENTE.INGREDIENTE_ID);
        public static final ForeignKey<ReceitaMetadadoRecord, ReceitaRecord> FK_RECEITA_METADADO_RECEITA1 = Internal.createForeignKey(com.fkfc.generatedsources.entity.Keys.KEY_RECEITA_PRIMARY, ReceitaMetadado.RECEITA_METADADO, "fk_receita_metadado_receita1", ReceitaMetadado.RECEITA_METADADO.RECEITA_ID);
        public static final ForeignKey<ReceitaMetadadoRecord, MetadadoRecord> FK_RECEITA_METADADO_TIPO_METADADO1 = Internal.createForeignKey(com.fkfc.generatedsources.entity.Keys.KEY_METADADO_PRIMARY, ReceitaMetadado.RECEITA_METADADO, "fk_receita_metadado_tipo_metadado1", ReceitaMetadado.RECEITA_METADADO.METADADO_ID);
    }
}
