/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity;


import com.fkfc.generatedsources.entity.tables.Categoria;
import com.fkfc.generatedsources.entity.tables.Ingrediente;
import com.fkfc.generatedsources.entity.tables.Metadado;
import com.fkfc.generatedsources.entity.tables.Receita;
import com.fkfc.generatedsources.entity.tables.ReceitaCategoria;
import com.fkfc.generatedsources.entity.tables.ReceitaIngrediente;
import com.fkfc.generatedsources.entity.tables.ReceitaMetadado;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Receitas extends SchemaImpl {

    private static final long serialVersionUID = 402100509;

    /**
     * The reference instance of <code>receitas</code>
     */
    public static final Receitas RECEITAS = new Receitas();

    /**
     * The table <code>receitas.categoria</code>.
     */
    public final Categoria CATEGORIA = com.fkfc.generatedsources.entity.tables.Categoria.CATEGORIA;

    /**
     * nom
     */
    public final Ingrediente INGREDIENTE = com.fkfc.generatedsources.entity.tables.Ingrediente.INGREDIENTE;

    /**
     * The table <code>receitas.metadado</code>.
     */
    public final Metadado METADADO = com.fkfc.generatedsources.entity.tables.Metadado.METADADO;

    /**
     * The table <code>receitas.receita</code>.
     */
    public final Receita RECEITA = com.fkfc.generatedsources.entity.tables.Receita.RECEITA;

    /**
     * The table <code>receitas.receita_categoria</code>.
     */
    public final ReceitaCategoria RECEITA_CATEGORIA = com.fkfc.generatedsources.entity.tables.ReceitaCategoria.RECEITA_CATEGORIA;

    /**
     * The table <code>receitas.receita_ingrediente</code>.
     */
    public final ReceitaIngrediente RECEITA_INGREDIENTE = com.fkfc.generatedsources.entity.tables.ReceitaIngrediente.RECEITA_INGREDIENTE;

    /**
     * The table <code>receitas.receita_metadado</code>.
     */
    public final ReceitaMetadado RECEITA_METADADO = com.fkfc.generatedsources.entity.tables.ReceitaMetadado.RECEITA_METADADO;

    /**
     * No further instances allowed
     */
    private Receitas() {
        super("receitas", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Categoria.CATEGORIA,
            Ingrediente.INGREDIENTE,
            Metadado.METADADO,
            Receita.RECEITA,
            ReceitaCategoria.RECEITA_CATEGORIA,
            ReceitaIngrediente.RECEITA_INGREDIENTE,
            ReceitaMetadado.RECEITA_METADADO);
    }
}
