/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity;


import com.fkfc.generatedsources.entity.tables.Categoria;
import com.fkfc.generatedsources.entity.tables.Ingrediente;
import com.fkfc.generatedsources.entity.tables.Metadado;
import com.fkfc.generatedsources.entity.tables.Receita;
import com.fkfc.generatedsources.entity.tables.ReceitaCategoria;
import com.fkfc.generatedsources.entity.tables.ReceitaIngrediente;
import com.fkfc.generatedsources.entity.tables.ReceitaMetadado;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in receitas
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>receitas.categoria</code>.
     */
    public static final Categoria CATEGORIA = com.fkfc.generatedsources.entity.tables.Categoria.CATEGORIA;

    /**
     * nom
     */
    public static final Ingrediente INGREDIENTE = com.fkfc.generatedsources.entity.tables.Ingrediente.INGREDIENTE;

    /**
     * The table <code>receitas.metadado</code>.
     */
    public static final Metadado METADADO = com.fkfc.generatedsources.entity.tables.Metadado.METADADO;

    /**
     * The table <code>receitas.receita</code>.
     */
    public static final Receita RECEITA = com.fkfc.generatedsources.entity.tables.Receita.RECEITA;

    /**
     * The table <code>receitas.receita_categoria</code>.
     */
    public static final ReceitaCategoria RECEITA_CATEGORIA = com.fkfc.generatedsources.entity.tables.ReceitaCategoria.RECEITA_CATEGORIA;

    /**
     * The table <code>receitas.receita_ingrediente</code>.
     */
    public static final ReceitaIngrediente RECEITA_INGREDIENTE = com.fkfc.generatedsources.entity.tables.ReceitaIngrediente.RECEITA_INGREDIENTE;

    /**
     * The table <code>receitas.receita_metadado</code>.
     */
    public static final ReceitaMetadado RECEITA_METADADO = com.fkfc.generatedsources.entity.tables.ReceitaMetadado.RECEITA_METADADO;
}
