-- MySQL Script generated by MySQL Workbench
-- seg 04 mar 2019 12:40:12 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema receitas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema receitas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `receitas` DEFAULT CHARACTER SET utf8 ;
USE `receitas` ;

-- -----------------------------------------------------
-- Table `receitas`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receitas`.`receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `modo_preparo` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `receitas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receitas`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `receitas`.`receita_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receitas`.`receita_categoria` (
  `receita_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  INDEX `fk_receita_categoria_receita1_idx` (`receita_id` ASC),
  INDEX `fk_receita_categoria_categoria1_idx` (`categoria_id` ASC),
  PRIMARY KEY (`receita_id`, `categoria_id`),
  CONSTRAINT `fk_receita_categoria_receita1`
    FOREIGN KEY (`receita_id`)
    REFERENCES `receitas`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_categoria_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `receitas`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `receitas`.`ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receitas`.`ingrediente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'nom';


-- -----------------------------------------------------
-- Table `receitas`.`receita_ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receitas`.`receita_ingrediente` (
  `receita_id` INT NOT NULL,
  `ingrediente_id` INT NOT NULL,
  `ordem` INT NOT NULL DEFAULT 0,
  `quantidade` VARCHAR(255) NULL,
  INDEX `fk_receita_ingrediente_receita1_idx` (`receita_id` ASC),
  INDEX `fk_receita_ingrediente_ingrediente1_idx` (`ingrediente_id` ASC),
  PRIMARY KEY (`receita_id`, `ingrediente_id`),
  CONSTRAINT `fk_receita_ingrediente_receita1`
    FOREIGN KEY (`receita_id`)
    REFERENCES `receitas`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_ingrediente_ingrediente1`
    FOREIGN KEY (`ingrediente_id`)
    REFERENCES `receitas`.`ingrediente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `receitas`.`metadado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receitas`.`metadado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `receitas`.`receita_metadado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `receitas`.`receita_metadado` (
  `receita_id` INT NOT NULL,
  `metadado_id` INT NOT NULL,
  `valor` VARCHAR(255) NULL,
  INDEX `fk_receita_metadado_receita1_idx` (`receita_id` ASC),
  INDEX `fk_receita_metadado_tipo_metadado1_idx` (`metadado_id` ASC),
  PRIMARY KEY (`metadado_id`, `receita_id`),
  CONSTRAINT `fk_receita_metadado_receita1`
    FOREIGN KEY (`receita_id`)
    REFERENCES `receitas`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_metadado_tipo_metadado1`
    FOREIGN KEY (`metadado_id`)
    REFERENCES `receitas`.`metadado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
