/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceitaCategoria implements Serializable {

    private static final long serialVersionUID = 633119876;

    private Integer receitaId;
    private Integer categoriaId;

    public ReceitaCategoria() {}

    public ReceitaCategoria(ReceitaCategoria value) {
        this.receitaId = value.receitaId;
        this.categoriaId = value.categoriaId;
    }

    public ReceitaCategoria(
        Integer receitaId,
        Integer categoriaId
    ) {
        this.receitaId = receitaId;
        this.categoriaId = categoriaId;
    }

    public Integer getReceitaId() {
        return this.receitaId;
    }

    public void setReceitaId(Integer receitaId) {
        this.receitaId = receitaId;
    }

    public Integer getCategoriaId() {
        return this.categoriaId;
    }

    public void setCategoriaId(Integer categoriaId) {
        this.categoriaId = categoriaId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReceitaCategoria (");

        sb.append(receitaId);
        sb.append(", ").append(categoriaId);

        sb.append(")");
        return sb.toString();
    }
}
