/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceitaIngrediente implements Serializable {

    private static final long serialVersionUID = -617427538;

    private Integer receitaId;
    private Integer ingredienteId;
    private Integer ordem;
    private String  quantidade;

    public ReceitaIngrediente() {}

    public ReceitaIngrediente(ReceitaIngrediente value) {
        this.receitaId = value.receitaId;
        this.ingredienteId = value.ingredienteId;
        this.ordem = value.ordem;
        this.quantidade = value.quantidade;
    }

    public ReceitaIngrediente(
        Integer receitaId,
        Integer ingredienteId,
        Integer ordem,
        String  quantidade
    ) {
        this.receitaId = receitaId;
        this.ingredienteId = ingredienteId;
        this.ordem = ordem;
        this.quantidade = quantidade;
    }

    public Integer getReceitaId() {
        return this.receitaId;
    }

    public void setReceitaId(Integer receitaId) {
        this.receitaId = receitaId;
    }

    public Integer getIngredienteId() {
        return this.ingredienteId;
    }

    public void setIngredienteId(Integer ingredienteId) {
        this.ingredienteId = ingredienteId;
    }

    public Integer getOrdem() {
        return this.ordem;
    }

    public void setOrdem(Integer ordem) {
        this.ordem = ordem;
    }

    public String getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReceitaIngrediente (");

        sb.append(receitaId);
        sb.append(", ").append(ingredienteId);
        sb.append(", ").append(ordem);
        sb.append(", ").append(quantidade);

        sb.append(")");
        return sb.toString();
    }
}
