/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Receita implements Serializable {

    private static final long serialVersionUID = 1791218720;

    private Integer id;
    private String  nome;
    private String  modoPreparo;

    public Receita() {}

    public Receita(Receita value) {
        this.id = value.id;
        this.nome = value.nome;
        this.modoPreparo = value.modoPreparo;
    }

    public Receita(
        Integer id,
        String  nome,
        String  modoPreparo
    ) {
        this.id = id;
        this.nome = nome;
        this.modoPreparo = modoPreparo;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getModoPreparo() {
        return this.modoPreparo;
    }

    public void setModoPreparo(String modoPreparo) {
        this.modoPreparo = modoPreparo;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Receita (");

        sb.append(id);
        sb.append(", ").append(nome);
        sb.append(", ").append(modoPreparo);

        sb.append(")");
        return sb.toString();
    }
}
