/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceitaMetadado implements Serializable {

    private static final long serialVersionUID = 195951734;

    private Integer receitaId;
    private Integer metadadoId;
    private String  valor;

    public ReceitaMetadado() {}

    public ReceitaMetadado(ReceitaMetadado value) {
        this.receitaId = value.receitaId;
        this.metadadoId = value.metadadoId;
        this.valor = value.valor;
    }

    public ReceitaMetadado(
        Integer receitaId,
        Integer metadadoId,
        String  valor
    ) {
        this.receitaId = receitaId;
        this.metadadoId = metadadoId;
        this.valor = valor;
    }

    public Integer getReceitaId() {
        return this.receitaId;
    }

    public void setReceitaId(Integer receitaId) {
        this.receitaId = receitaId;
    }

    public Integer getMetadadoId() {
        return this.metadadoId;
    }

    public void setMetadadoId(Integer metadadoId) {
        this.metadadoId = metadadoId;
    }

    public String getValor() {
        return this.valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReceitaMetadado (");

        sb.append(receitaId);
        sb.append(", ").append(metadadoId);
        sb.append(", ").append(valor);

        sb.append(")");
        return sb.toString();
    }
}
