/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables;


import com.fkfc.generatedsources.entity.Indexes;
import com.fkfc.generatedsources.entity.Keys;
import com.fkfc.generatedsources.entity.Receitas;
import com.fkfc.generatedsources.entity.tables.records.IngredienteRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * nom
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ingrediente extends TableImpl<IngredienteRecord> {

    private static final long serialVersionUID = 424105476;

    /**
     * The reference instance of <code>receitas.ingrediente</code>
     */
    public static final Ingrediente INGREDIENTE = new Ingrediente();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IngredienteRecord> getRecordType() {
        return IngredienteRecord.class;
    }

    /**
     * The column <code>receitas.ingrediente.id</code>.
     */
    public final TableField<IngredienteRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>receitas.ingrediente.nome</code>.
     */
    public final TableField<IngredienteRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>receitas.ingrediente</code> table reference
     */
    public Ingrediente() {
        this(DSL.name("ingrediente"), null);
    }

    /**
     * Create an aliased <code>receitas.ingrediente</code> table reference
     */
    public Ingrediente(String alias) {
        this(DSL.name(alias), INGREDIENTE);
    }

    /**
     * Create an aliased <code>receitas.ingrediente</code> table reference
     */
    public Ingrediente(Name alias) {
        this(alias, INGREDIENTE);
    }

    private Ingrediente(Name alias, Table<IngredienteRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ingrediente(Name alias, Table<IngredienteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("nom"));
    }

    public <O extends Record> Ingrediente(Table<O> child, ForeignKey<O, IngredienteRecord> key) {
        super(child, key, INGREDIENTE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Receitas.RECEITAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.INGREDIENTE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IngredienteRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INGREDIENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<IngredienteRecord> getPrimaryKey() {
        return Keys.KEY_INGREDIENTE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<IngredienteRecord>> getKeys() {
        return Arrays.<UniqueKey<IngredienteRecord>>asList(Keys.KEY_INGREDIENTE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ingrediente as(String alias) {
        return new Ingrediente(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ingrediente as(Name alias) {
        return new Ingrediente(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingrediente rename(String name) {
        return new Ingrediente(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ingrediente rename(Name name) {
        return new Ingrediente(name, null);
    }
}
