/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables;


import com.fkfc.generatedsources.entity.Indexes;
import com.fkfc.generatedsources.entity.Keys;
import com.fkfc.generatedsources.entity.Receitas;
import com.fkfc.generatedsources.entity.tables.records.MetadadoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Metadado extends TableImpl<MetadadoRecord> {

    private static final long serialVersionUID = 1710088324;

    /**
     * The reference instance of <code>receitas.metadado</code>
     */
    public static final Metadado METADADO = new Metadado();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetadadoRecord> getRecordType() {
        return MetadadoRecord.class;
    }

    /**
     * The column <code>receitas.metadado.id</code>.
     */
    public final TableField<MetadadoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>receitas.metadado.nome</code>.
     */
    public final TableField<MetadadoRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>receitas.metadado</code> table reference
     */
    public Metadado() {
        this(DSL.name("metadado"), null);
    }

    /**
     * Create an aliased <code>receitas.metadado</code> table reference
     */
    public Metadado(String alias) {
        this(DSL.name(alias), METADADO);
    }

    /**
     * Create an aliased <code>receitas.metadado</code> table reference
     */
    public Metadado(Name alias) {
        this(alias, METADADO);
    }

    private Metadado(Name alias, Table<MetadadoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Metadado(Name alias, Table<MetadadoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Metadado(Table<O> child, ForeignKey<O, MetadadoRecord> key) {
        super(child, key, METADADO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Receitas.RECEITAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.METADADO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MetadadoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_METADADO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MetadadoRecord> getPrimaryKey() {
        return Keys.KEY_METADADO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MetadadoRecord>> getKeys() {
        return Arrays.<UniqueKey<MetadadoRecord>>asList(Keys.KEY_METADADO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Metadado as(String alias) {
        return new Metadado(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Metadado as(Name alias) {
        return new Metadado(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Metadado rename(String name) {
        return new Metadado(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Metadado rename(Name name) {
        return new Metadado(name, null);
    }
}
