/*
 * This file is generated by jOOQ.
 */
package com.fkfc.generatedsources.entity.tables;


import com.fkfc.generatedsources.entity.Indexes;
import com.fkfc.generatedsources.entity.Keys;
import com.fkfc.generatedsources.entity.Receitas;
import com.fkfc.generatedsources.entity.tables.records.ReceitaCategoriaRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceitaCategoria extends TableImpl<ReceitaCategoriaRecord> {

    private static final long serialVersionUID = -695886514;

    /**
     * The reference instance of <code>receitas.receita_categoria</code>
     */
    public static final ReceitaCategoria RECEITA_CATEGORIA = new ReceitaCategoria();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReceitaCategoriaRecord> getRecordType() {
        return ReceitaCategoriaRecord.class;
    }

    /**
     * The column <code>receitas.receita_categoria.receita_id</code>.
     */
    public final TableField<ReceitaCategoriaRecord, Integer> RECEITA_ID = createField("receita_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>receitas.receita_categoria.categoria_id</code>.
     */
    public final TableField<ReceitaCategoriaRecord, Integer> CATEGORIA_ID = createField("categoria_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>receitas.receita_categoria</code> table reference
     */
    public ReceitaCategoria() {
        this(DSL.name("receita_categoria"), null);
    }

    /**
     * Create an aliased <code>receitas.receita_categoria</code> table reference
     */
    public ReceitaCategoria(String alias) {
        this(DSL.name(alias), RECEITA_CATEGORIA);
    }

    /**
     * Create an aliased <code>receitas.receita_categoria</code> table reference
     */
    public ReceitaCategoria(Name alias) {
        this(alias, RECEITA_CATEGORIA);
    }

    private ReceitaCategoria(Name alias, Table<ReceitaCategoriaRecord> aliased) {
        this(alias, aliased, null);
    }

    private ReceitaCategoria(Name alias, Table<ReceitaCategoriaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ReceitaCategoria(Table<O> child, ForeignKey<O, ReceitaCategoriaRecord> key) {
        super(child, key, RECEITA_CATEGORIA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Receitas.RECEITAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_CATEGORIA1_IDX, Indexes.RECEITA_CATEGORIA_FK_RECEITA_CATEGORIA_RECEITA1_IDX, Indexes.RECEITA_CATEGORIA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReceitaCategoriaRecord> getPrimaryKey() {
        return Keys.KEY_RECEITA_CATEGORIA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReceitaCategoriaRecord>> getKeys() {
        return Arrays.<UniqueKey<ReceitaCategoriaRecord>>asList(Keys.KEY_RECEITA_CATEGORIA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReceitaCategoriaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReceitaCategoriaRecord, ?>>asList(Keys.FK_RECEITA_CATEGORIA_RECEITA1, Keys.FK_RECEITA_CATEGORIA_CATEGORIA1);
    }

    public Receita receita() {
        return new Receita(this, Keys.FK_RECEITA_CATEGORIA_RECEITA1);
    }

    public Categoria categoria() {
        return new Categoria(this, Keys.FK_RECEITA_CATEGORIA_CATEGORIA1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceitaCategoria as(String alias) {
        return new ReceitaCategoria(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ReceitaCategoria as(Name alias) {
        return new ReceitaCategoria(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReceitaCategoria rename(String name) {
        return new ReceitaCategoria(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReceitaCategoria rename(Name name) {
        return new ReceitaCategoria(name, null);
    }
}
